/**
 * Canonical static figure paths for record-mode deploy (no .dat).
 * Keep brush band / findings verify mappings in one place.
 */

export type BrushBandId = 'bottom' | 'mid' | 'filament' | 'top';

/** Band preview PNGs — generated by tools/python/export_band_previews.py (BandPreviewCanvas parity). */
export const VIDEO_BRUSH_BAND_FIGURES: Record<BrushBandId, string> = {
  bottom: 'task4_band_bottom_t99.png',
  mid: 'task4_band_mid_t99.png',
  filament: 'task4_band_filament_t99.png',
  top: 'task4_band_top_t99.png',
};

export const VIDEO_BRUSH_BAND_FALLBACKS: Partial<Record<BrushBandId, string>> = {
  bottom: 'task4_brush_bottom_hl.png',
  mid: 'task4_discovery_context_t99.png',
  filament: 'task4_spatial_filament.png',
  top: 'task4_brush_top1_viz.png',
};

/** Findings card 04 — spatial verify (square highlight projections). */
export const VIDEO_FINDINGS_VERIFY = {
  top: 'task4_brush_top1_viz.png',
  topFallback: 'task4_brush_top1.png',
  bottom: 'task4_brush_bottom_hl.png',
  bottomFallback: 'task4_brush_bottom_proj.png',
} as const;

/** Poster / report brush verify rows. */
export const VIDEO_POSTER_BRUSH_VERIFY = {
  top: 'task4_brush_top1.png',
  bottom: 'task4_brush_bottom_hl.png',
} as const;

/** All PNGs referenced above — used by verify_nyxviz_static.ps1. */
export const VIDEO_STATIC_FIGURE_PATHS: readonly string[] = [
  ...Object.values(VIDEO_BRUSH_BAND_FIGURES),
  ...Object.values(VIDEO_BRUSH_BAND_FALLBACKS),
  VIDEO_FINDINGS_VERIFY.top,
  VIDEO_FINDINGS_VERIFY.topFallback,
  VIDEO_FINDINGS_VERIFY.bottom,
  VIDEO_FINDINGS_VERIFY.bottomFallback,
  VIDEO_POSTER_BRUSH_VERIFY.top,
  VIDEO_POSTER_BRUSH_VERIFY.bottom,
];
